/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Login;

import java.awt.Color;
import user.Admin;
import user.DoctorForm;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.plaf.OptionPaneUI;
import user.LaboratoryForm;
import user.ReceptionistForm;

/**
 *
 * @author KasunDissanayake
 */
public class Login extends javax.swing.JFrame {
    Connection conn;
    Statement stm;
    ResultSet rst;
    String un,p;

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        //PASSWORD FIELD SET TO EMPTY
        passtxt.setText("");
        //CHANGE THE BACKGROUND COLOURS
        getContentPane().setBackground(Color.gray);
        jPanel1.setBackground(Color.LIGHT_GRAY);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        loginbtn = new javax.swing.JButton();
        exitbtn = new javax.swing.JButton();
        username = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        userTxt = new javax.swing.JTextField();
        passtxt = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        loginbtn.setText("Login");
        loginbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbtnActionPerformed(evt);
            }
        });

        exitbtn.setText("Exit");
        exitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbtnActionPerformed(evt);
            }
        });

        username.setText("USERNAME");

        password.setText("PASSWORD");

        userTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userTxtActionPerformed(evt);
            }
        });

        passtxt.setText("jPasswordField1");
        passtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passtxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(username)
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(passtxt)
                            .addComponent(userTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE))
                        .addGap(0, 51, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(password)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(exitbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(95, 95, 95)
                                .addComponent(loginbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(username))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(userTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(password)
                    .addComponent(passtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 222, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exitbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 173, 430, 500));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setText("                            LOGIN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 648, 41));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/logo.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 90, 470, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userTxtActionPerformed

    private void loginbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbtnActionPerformed
        try {
            //GET THE CONNECTION
            Class.forName("com.mysql.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/hms","root","");
            stm=conn.createStatement();
            //EXECUTE THE QUERY
            String qry="SELECT Staff_ID,Password from admin";
            rst=stm.executeQuery(qry);
            //GET THE USERNAME AND THE PASSWORD TEXT TO VARIABLES 
            un=userTxt.getText();
            p=passtxt.getText();
            int k=0;  
            //CHECK FROM THE ADMIN TABLE WHETHER USER INPUT IS CORRECT OR NOT
            while (rst.next()) {
                String u1=rst.getString(1);
                String p1=rst.getString(2);
                
                if (un.equals(u1)) {
                    k=1;
                    if (p.equals(p1)) {
                        //IF CORRECT GO THE ADMIN PAGE
                        JOptionPane.showMessageDialog(this,"Login Successful","SUCCESS",JOptionPane.INFORMATION_MESSAGE);
                        Admin ad=new Admin();
                        ad.setVisible(true);
                        ad.setLocationRelativeTo(null);
                        userTxt.setText("");
                        passtxt.setText("");
                        this.dispose();
                        break;
                                       
                    }else{
                        //IF WRONG SHOW ERROR MESSAGE
                        JOptionPane.showMessageDialog(this,"Password Incorrect","ERROR",JOptionPane.ERROR_MESSAGE);
                        passtxt.setText("");
                        break;
                
                    }
                }
                
            }
            //CHECK FROM THE DOCTOR TABLE WHETHER THE USER INPUTS ARE CORRECT
            String qry1="SELECT Staff_ID,Password from doctor";
            rst=stm.executeQuery(qry1);
            un=userTxt.getText();
            p=passtxt.getText();
                     
            while (rst.next()) {
                String u1=rst.getString(1);
                String p1=rst.getString(2);
                
                if (un.equals(u1)) {
                    k=1;
                    if (p.equals(p1)) {
                        //IF CORRECT GO TO THE DOCTOR FORM
                        JOptionPane.showMessageDialog(this,"Login Successful","SUCCESS",JOptionPane.INFORMATION_MESSAGE);
                        DoctorForm df=new DoctorForm();
                        df.setVisible(true);
                        userTxt.setText("");
                        passtxt.setText("");
                        this.dispose();
                        break;
                                       
                    }else{
                        //IF WRONG SHOW ERROR MESSAGE
                        JOptionPane.showMessageDialog(this,"Password Incorrect","ERROR",JOptionPane.ERROR_MESSAGE);
                        passtxt.setText("");
                        break;
                
                    }
                }
                
            }
            //CHECK FROM THE LABORATORY FORM WHETHER USER INPUTS ARE CORRECT
            String qry2="SELECT Staff_ID,Password from laboratory";
            rst=stm.executeQuery(qry2);
            un=userTxt.getText();
            p=passtxt.getText();
                      
            while (rst.next()) {
                String u1=rst.getString(1);
                String p1=rst.getString(2);
                
                if (un.equals(u1)) {
                    k=1;
                    if (p.equals(p1)) {
                        //IF CORRECT GO TO THE LABORATORY FORM
                        JOptionPane.showMessageDialog(this,"Login Successful","SUCCESS",JOptionPane.INFORMATION_MESSAGE);
                        LaboratoryForm lb=new LaboratoryForm();
                        lb.setVisible(true);
                        userTxt.setText("");
                        passtxt.setText("");
                        this.dispose();
                        break;
                                       
                    }else{
                        //IF WRONG SHOW ERROR MESSAGE
                        JOptionPane.showMessageDialog(this,"Password Incorrect","ERROR",JOptionPane.ERROR_MESSAGE);
                        passtxt.setText("");
                        break;
                
                    }
                }
                
            }
            //CHECK FROM THE RECEPTIONIST FORM WHETHER USER INPUTS ARE COORRECT
            String qry3="SELECT Staff_ID,Password from receptionist";
            rst=stm.executeQuery(qry3);
            un=userTxt.getText();
            p=passtxt.getText();
                    
            while (rst.next()) {
                String u1=rst.getString(1);
                String p1=rst.getString(2);
                
                if (un.equals(u1)) {
                    k=1;
                    if (p.equals(p1)) {
                        //IF CORRECT GO TO THE RECEPTIONIST FORM
                        JOptionPane.showMessageDialog(this,"Login Successful","SUCCESS",JOptionPane.INFORMATION_MESSAGE);
                        ReceptionistForm rf=new ReceptionistForm();
                        rf.setVisible(true);
                        userTxt.setText("");
                        passtxt.setText("");
                        this.dispose();
                        break;
                                       
                    }else{
                        //IF WRONG SHOW ERROR MESSAGE
                        JOptionPane.showMessageDialog(this,"Password Incorrect","ERROR",JOptionPane.ERROR_MESSAGE);
                        passtxt.setText("");
                        break;
                
                    }
                }
                
            }
            
            if (k==0) {
                //CANNOT FIND USER INPUT USERNAME NAME FROM THE TABLES
                JOptionPane.showMessageDialog(this,"Invalid Username","ERROR",JOptionPane.ERROR_MESSAGE);
            }
            passtxt.setText("");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        
    }//GEN-LAST:event_loginbtnActionPerformed

    private void exitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_exitbtnActionPerformed

    private void passtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passtxtActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_passtxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exitbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loginbtn;
    private javax.swing.JPasswordField passtxt;
    private javax.swing.JLabel password;
    private javax.swing.JTextField userTxt;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
