/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package registration;

import java.awt.Color;
import java.net.ConnectException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author KasunDissanayake
 */
public class PatientRegistration extends javax.swing.JFrame {
    //INITIALIZE THE VARIABLES
    Connection conn;
    Statement st;
    ResultSet rst,rst1;
    String nic,name,address,gender,tel,age,checkin,ward,bed,disease,payment,paid,enter_date,recomand,confirm;
    


    /**
     * Creates new form PatientRegistration
     */
    public PatientRegistration() {
        initComponents();
        //CALL METHOD GROUPBUTTON()
        groupButton();
        //CHANGE THE BACKGROUND COLOURS
        getContentPane().setBackground(Color.gray);
        jPanel1.setBackground(Color.LIGHT_GRAY);
        jPanel2.setBackground(Color.LIGHT_GRAY);
        jPanel3.setBackground(Color.LIGHT_GRAY);
        //GET THE CURRENT DATE
        DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");
        Date date = new Date();
        //SET THE DATE TO CURRENT DATE
        t13.setText(dateFormat.format(date));
        
    }
    private void groupButton( ) {
            //KEEP THE BUTTON TO ONE CHOICES .USER CANNOT CHOOSE TWO OPTIONS.HE CAN CHOSE ONLY ONE OPTION
            ButtonGroup bg1 = new ButtonGroup( );
            bg1.add(jRadioButton1);
            bg1.add(jRadioButton2);


}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        t1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        t2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        t3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        t5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        t6 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        t7 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        t8 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        t9 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        t11 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        t12 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        t13 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        t10 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel16 = new javax.swing.JLabel();
        t14 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        t15 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        tt1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        tt2 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setText("Patient Registration");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(416, 21, 374, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel2.setText("NIC");

        jLabel3.setText("Name");

        jLabel4.setText("Address");

        jLabel5.setText("Gender");

        jLabel6.setText("Phone");

        jLabel7.setText("Age");

        jLabel8.setText("Checkin");

        jLabel9.setText("Ward No");

        jLabel10.setText("Bed No");

        jLabel12.setText("Payment");

        t11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t11ActionPerformed(evt);
            }
        });

        jLabel13.setText("Paid");

        t12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t12ActionPerformed(evt);
            }
        });

        jLabel14.setText("Date");

        t13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t13ActionPerformed(evt);
            }
        });

        jLabel11.setText("Disease");

        t10.setColumns(20);
        t10.setRows(5);
        jScrollPane1.setViewportView(t10);

        jButton1.setText("Register");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jRadioButton1.setText("MALE");

        jRadioButton2.setText("FEMALE");

        jLabel16.setText("Recommand By");

        jLabel17.setText("Confirmed By");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel14)
                            .addGap(25, 25, 25)))
                    .addComponent(jLabel11)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addGap(126, 126, 126)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(t15)
                        .addGap(62, 62, 62))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                                .addComponent(jRadioButton2))
                            .addComponent(t9, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(t8, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(t7, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(t6, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(t5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(t3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(t2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(t1))
                        .addGap(66, 66, 66))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(t14, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(t13, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(t11, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(t12, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(62, 62, 62))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(t3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(t5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(t6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(t7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(t8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(t9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(t11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(t12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(t13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel11))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(t14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(t15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jButton1)
                .addGap(22, 22, 22))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 86, -1, 820));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jButton3.setText("Update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        tt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tt1ActionPerformed(evt);
            }
        });

        jButton2.setText("Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(tt1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(155, 155, 155))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(74, 74, 74)
                .addComponent(jButton3)
                .addContainerGap(181, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(595, 86, -1, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jButton4.setText("Delete");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Search");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(tt2, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(145, 145, 145))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5))
                .addGap(74, 74, 74)
                .addComponent(jButton4)
                .addContainerGap(128, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(595, 520, 476, 340));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/logo.png"))); // NOI18N
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, 450, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        try {
            //GET THE CONNECTION            
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost/hms","root","");            
            st = conn.createStatement();
            //CREATE VARIABLE K AND ASSIGN ZERO TO IT
            int k=0;
            //GET DATA FROM THE USER
            nic=t1.getText();
            name=t2.getText();
            address=t3.getText();
            //GENDER SELECTION FROM THE RADIO BUTTON
            if (jRadioButton1.isSelected()) {
                gender=jRadioButton1.getText();
            }
            else if (jRadioButton2.isSelected()) {
                gender=jRadioButton2.getText();
            }
            
            tel=t5.getText();
            age=t6.getText();
            checkin=t7.getText();
            ward=t8.getText();
            bed=t9.getText();
            disease=t10.getText();
            payment=t11.getText();
            paid=t12.getText();
            enter_date=t13.getText();
            recomand=t14.getText();
            confirm=t15.getText();
            
            //Checking ward maximum of beds
            String qry="SELECT * FROM ward where ward_No='"+ward+"'";            
            ResultSet rs = st.executeQuery(qry);  
            rs.next();
            int b=Integer.parseInt(rs.getString(2));
            //Checking free beds
            String qry1="SELECT Bed_No FROM patientdetails where Ward='"+ward+"'";
            ResultSet rs1= st.executeQuery(qry1);
            while(rs1.next()){
                if(rs1.getString(1).equals(bed)){
                    k=1;
                }            
            }
            //Checking condition maximum beds and free beds
            if(b>=Integer.parseInt(bed) && k==0){
                int have_to_pay=Integer.parseInt(payment)-Integer.parseInt(paid);
                st.executeUpdate("INSERT INTO patientdetails VALUES('"+nic+"','"+name+"','"+address+"','"+gender+"','"+tel+"','"+age+"','"+checkin+"','"+ward+"','"+bed+"','"+disease+"','"+recomand+"','"+confirm+"')");
                JOptionPane.showMessageDialog(this, "Patient Registered", "SUCCESS", JOptionPane.INFORMATION_MESSAGE);
                int dialogButton = JOptionPane.YES_NO_OPTION;
                JOptionPane.showConfirmDialog (null, "Would You Like to assign this patient to Doctor???","Warning",dialogButton);
                //ASSIGN PATIENT TO A DOCTOR
                if(dialogButton == JOptionPane.YES_OPTION){   
                    AssignForm as=new AssignForm(checkin,ward);
                    as.setVisible(true);
                    

                    
                    }
                //UPDATE DATA TO WARD AND PAYMENT TABLES
                st.executeUpdate("INSERT INTO ward_details VALUES('"+ward+"','"+b+"','"+name+"','"+checkin+"','"+bed+"')");
                st.executeUpdate("INSERT INTO payment VALUES('"+checkin+"','"+payment+"','"+paid+"','"+have_to_pay+"','"+enter_date+"')");
               
                this.dispose();
            }
            //NOTICE THE BED IS RESERVED
            else if (k==1) {
                JOptionPane.showMessageDialog(this, "This bed is reserved", "ERROR", JOptionPane.INFORMATION_MESSAGE);
            }
            //NOTICE THE MAXIMUM RATE OF BEDS
            else{
                JOptionPane.showMessageDialog(this, "This ward has maximum "+b+" beds", "ERROR", JOptionPane.INFORMATION_MESSAGE);
            
            }
            
        } catch (Exception ex) {
            System.out.println(ex);
        }
            
            
            
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void t12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t12ActionPerformed

    private void t11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t11ActionPerformed

    private void t13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t13ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            //CREATE CONNECTION
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost/hms","root",""); 
            //GET THE NEW DATA FROM THE USER
            st = conn.createStatement();            
            nic=t1.getText();
            name=t2.getText();
            address=t3.getText();
            //SELECT THE GENDER FROM RADIO BUTTONS
            if (jRadioButton1.isSelected()) {
                gender=jRadioButton1.getText();
            }
            else if (jRadioButton2.isSelected()) {
                gender=jRadioButton2.getText();
            }
            tel=t5.getText();
            age=t6.getText();
            checkin=t7.getText();
            ward=t8.getText();
            bed=t9.getText();
            disease=t10.getText();
            payment=t11.getText();
            paid=t12.getText();
            enter_date=t13.getText();
            recomand=t14.getText();
            confirm=t15.getText();
            int k=0;
            String qry="SELECT * FROM ward where ward_No='"+ward+"'";            
            ResultSet rs = st.executeQuery(qry);  
            rs.next();
            int b=Integer.parseInt(rs.getString(2));
            //Checking free beds
            String qry1="SELECT Bed_No,Check_in FROM patientdetails where Ward='"+ward+"'";
            ResultSet rs1= st.executeQuery(qry1);
            
            while(rs1.next()){
                if(rs1.getString(1).equals(bed) && !(rs1.getString(2).equals(checkin))){
                    System.out.println(rs1.getString(2));
                    System.out.println(checkin);
                    k=1;
                }            
            }
            //Checking condition maximum beds and free beds
            if(b>=Integer.parseInt(bed) && k==0){
                int have_to_pay=Integer.parseInt(payment)-Integer.parseInt(paid);
                System.out.println(bed);
                st.executeUpdate("UPDATE  patientdetails SET NIC='"+nic+"',Name='"+name+"',Address='"+address+"',Gender='"+gender+"',Phone='"+tel+"',Age='"+age+"',Check_in='"+checkin+"',Ward='"+ward+"',Bed_No='"+bed+"',Disease='"+disease+"',recommandation='"+recomand+"',confirmation='"+confirm+"' WHERE Check_in='"+tt1.getText()+"' ");  
                st.executeUpdate("UPDATE  payment SET check_in='"+checkin+"',payment='"+payment+"',paid='"+paid+"',have_to_pay='"+have_to_pay+"',enter_date='"+enter_date+"' WHERE check_in='"+tt1.getText()+"' "); 
                st.executeUpdate("UPDATE  ward_details SET ward_no='"+ward+"' ,beds='"+b+"',name='"+name+"',check_in='"+checkin+"',bed_no='"+bed+"' WHERE check_in='"+tt1.getText()+"' ");
                JOptionPane.showMessageDialog(this, "Updated", "ERROR", JOptionPane.INFORMATION_MESSAGE);
                
                this.dispose();
            }
            else if (k==1  ) {
                JOptionPane.showMessageDialog(this, "This bed is reserved", "ERROR", JOptionPane.INFORMATION_MESSAGE);
            }
            else{
                JOptionPane.showMessageDialog(this, "This ward has maximum "+b+" beds", "ERROR", JOptionPane.INFORMATION_MESSAGE);
            
            }     
        } catch (Exception ex) {
            System.out.println(ex);
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            //CREATE CONNECTION
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost/hms","root","");            
            st = conn.createStatement();            
            checkin=t7.getText();    
            String qry="DELETE FROM patientdetails WHERE Check_in='"+tt2.getText()+"' ";  
            String qry1="DELETE FROM payment WHERE check_in='"+tt2.getText()+"' "; 
            String qry2="DELETE FROM ward_details WHERE Check_in='"+tt2.getText()+"' "; 
            JOptionPane.showMessageDialog(this, "Deleted", "SUCCESS", JOptionPane.INFORMATION_MESSAGE);
            //EXECUTE DELETE QUERIES
            st.executeUpdate(qry);
            st.executeUpdate(qry1);
            st.executeUpdate(qry2);
            
            
            
            
            
            
            
        } catch (Exception ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            //GET THE USER INPUT(PATIENT CHECKIN NUMBER)
            String search=tt1.getText();
            //CREATE CONNECTION
            Class.forName("com.mysql.jdbc.Driver");            
            conn = DriverManager.getConnection("jdbc:mysql://localhost/hms","root","");
            Statement stm = conn.createStatement();
            String qry="SELECT * FROM patientdetails WHERE Check_in = '"+search+"' ";
            String qry1="SELECT * FROM payment WHERE check_in='"+search+"'";
                        
            
            
            int p=0;
            //CHECK VALID INPUT
            if (search.equals("")) {
                JOptionPane.showMessageDialog(this, "Please enter the Check in number to Update.", "ERROR", JOptionPane.INFORMATION_MESSAGE);
                
            }
            
            else{
                //NO PATIENTS
                rst=stm.executeQuery(qry);   
                
                if (!rst.next()) {
                    JOptionPane.showMessageDialog(this, "Invalid Check in Number", "ERROR", JOptionPane.INFORMATION_MESSAGE);
                }
                else{
                //PUT DATA TO TEXT FIELDS   
                t1.setText(rst.getString(1));
                t2.setText(rst.getString(2));
                t3.setText(rst.getString(3));
                if (rst.getString(4).toLowerCase().equals("male")) {
                    jRadioButton1.setSelected(true);
                }
                else if (rst.getString(4).toLowerCase().equals("female") ){
                    jRadioButton2.setSelected(true);
                }
                t5.setText(rst.getString(5));
                t6.setText(rst.getString(6));
                t7.setText(rst.getString(7));
                t8.setText(rst.getString(8));
                t9.setText(rst.getString(9));
                t10.setText(rst.getString(10));
                t14.setText(rst.getString(11));
                t15.setText(rst.getString(12));
                rst1=stm.executeQuery(qry1); 
                    if (rst1.next()==false) {
                        JOptionPane.showMessageDialog(this, "Invalid Check in Number", "ERROR", JOptionPane.INFORMATION_MESSAGE);
                    }
                    else{
                        t11.setText(rst1.getString(2));
                        t12.setText(rst1.getString(3));
                        t13.setText(rst1.getString(5));
                    }
                }
                
                
            }
        } catch (Exception ex) {
            System.err.println(ex);
        }
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tt1ActionPerformed
        
    }//GEN-LAST:event_tt1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            String search=tt2.getText();
            System.out.println(search);
            Class.forName("com.mysql.jdbc.Driver");            
            conn = DriverManager.getConnection("jdbc:mysql://localhost/hms","root","");
            Statement stm = conn.createStatement();
            String qry="SELECT * FROM patientdetails WHERE Check_in = '"+search+"' ";
            String qry1="SELECT * FROM payment WHERE check_in='"+search+"'";
                        
            
            
            int p=0;
            
            if (search.equals("")) {
                JOptionPane.showMessageDialog(this, "Please enter the Check in number to Delete.", "ERROR", JOptionPane.INFORMATION_MESSAGE);
                
            }
            
            else{
                rst=stm.executeQuery(qry);                 
                if (rst.next()==false) {
                    JOptionPane.showMessageDialog(this, "Invalid Check in Number", "ERROR", JOptionPane.INFORMATION_MESSAGE);
                }
                else{
                t1.setText(rst.getString(1));
                t2.setText(rst.getString(2));
                t3.setText(rst.getString(3));
                if (rst.getString(4).toLowerCase().equals("male")) {
                    jRadioButton1.setSelected(true);
                }
                else if (rst.getString(4).toLowerCase().equals("female") ){
                    jRadioButton2.setSelected(true);
                }
                t5.setText(rst.getString(5));
                t6.setText(rst.getString(6));
                t7.setText(rst.getString(7));
                t8.setText(rst.getString(8));
                t9.setText(rst.getString(9));
                t10.setText(rst.getString(10));
                t14.setText(rst.getString(11));
                t15.setText(rst.getString(12));
                rst1=stm.executeQuery(qry1); 
                    if (rst1.next()==false) {
                        JOptionPane.showMessageDialog(this, "Invalid Check in Number", "ERROR", JOptionPane.INFORMATION_MESSAGE);
                    }
                    else{
                        
                        t11.setText(rst1.getString(2));
                        t12.setText(rst1.getString(3));
                        t13.setText(rst1.getString(5));
                    }
                }
                
                
            }
        } catch (Exception ex) {
            System.err.println(ex);
        }
        
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PatientRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PatientRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PatientRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatientRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PatientRegistration().setVisible(true);
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField t1;
    private javax.swing.JTextArea t10;
    private javax.swing.JTextField t11;
    private javax.swing.JTextField t12;
    private javax.swing.JTextField t13;
    private javax.swing.JTextField t14;
    private javax.swing.JTextField t15;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t5;
    private javax.swing.JTextField t6;
    private javax.swing.JTextField t7;
    private javax.swing.JTextField t8;
    private javax.swing.JTextField t9;
    private javax.swing.JTextField tt1;
    private javax.swing.JTextField tt2;
    // End of variables declaration//GEN-END:variables
}
